### ISSUE TITLE
test 3

### ISSUE THREAD

**Issue by Rick-29** [theshadow76/BinaryOptionsTools#17]
example content

**Comment by toxicpandas** [comment]
BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'
BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'
BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'
BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'
BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'
BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'
