### ISSUE TITLE
main.py 

### ISSUE THREAD

**Issue by Lestanen** [theshadow76/BinaryOptionsTools#3]
Hello there. im getting this error 
`True
Connecting...
CONNECTED SUCCESSFUL
GET BALANCE: 33.06
                   time     open     high      low    close
0   2024-10-22 18:09:10  1.08133  1.08134  1.08133  1.08134
1   2024-10-22 18:09:11  1.08133  1.08133  1.08131  1.08131
2   2024-10-22 18:09:12  1.08127  1.08127  1.08126  1.08126
3   2024-10-22 18:09:13  1.08126  1.08126  1.08125  1.08125
4   2024-10-22 18:09:14  1.08126  1.08128  1.08126  1.08128
..                  ...      ...      ...      ...      ...
414 2024-10-22 18:16:04  1.08107  1.08112  1.08107  1.08112
415 2024-10-22 18:16:05  1.08112  1.08112  1.08111  1.08111
416 2024-10-22 18:16:06  1.08111  1.08115  1.08111  1.08115
417 2024-10-22 18:16:07  1.08107  1.08107  1.08107  1.08107
418 2024-10-22 18:16:08  1.08107  1.08107  1.08107  1.08107

[419 rows x 5 columns]
C:\Users\iop\env\src\binaryoptionstools\test.py:97: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they
are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(r"C:\Users\iop\env\src\binaryoptionstools\binary_options_model2.pth"))
Placing a 'put' trade.
ERROR:root:Unknown error occurred during buy operation
C:\Users\iop\env\src\binaryoptionstools\test.py:97: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they
are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(r"C:\Users\iop\env\src\binaryoptionstools\binary_options_model2.pth"))
Placing a 'put' trade.`
i changed ` model.load_state_dict(torch.load(r"C:\Users\iop\env\src\binaryoptionstools\binary_options_model2.pth" , weights_only=True))` but still `Placing a 'call' trade.
ERROR:root:Unknown error occurred during buy operation`

**Comment by theshadow76** [comment]
Hi, the that's a test file, for now, thoes model do not fully work, and are not that accurate!
Talk to me in discord if you need more help!!!

**Comment by theshadow76** [comment]
Talk to us in discord if you need more help
