### ISSUE TITLE
GetCandles

### ISSUE THREAD

**Issue by AndreasStgt** [theshadow76/BinaryOptionsTools#9]
api.GetCandles used as shown in the sma.crossover example always return Error processing candles, 'time'

**Comment by theshadow76** [comment]
Let me check

**Comment by AndreasStgt** [comment]
Sorry,seems i have been mistaken. Maybe it was a temporary problem

**Comment by AndreasStgt** [comment]
Now i have it again

**Comment by theshadow76** [comment]
Great

**Comment by theshadow76** [comment]
> Now i have it again

Okey, same traceback?

**Comment by AndreasStgt** [comment]
Yes, from the same statement.
Df=api.GetCandles("EURUSD_otc",1,100) for example. I don't know why it was working one time, but again i always get error processing candles

**Comment by theshadow76** [comment]
Okey, we will Look into it
